"""
predict_mlp.py — forward passes, density plots, and benchmark scatter for the
Dense MLP log-normal mixture model.

Two modes:

    # one sequence -> moments + continuous density plot
    python predict_mlp.py single --seq MDVFMKGLSK... --out rg_density.png

    # a YAML of sequences -> table + CSV + benchmark scatter vs reference Rg
    python predict_mlp.py benchmark --yaml config/sequences.yaml --out bench.png

────────────────────────────────────────────────────────────────────────────────
DESIGN NOTE — Single source of truth.
This file imports from mlp_mixture and bigru_mixture. If the physics transforms
or head calculations adjust, this script updates automatically or fails loudly.
────────────────────────────────────────────────────────────────────────────────
"""
from __future__ import annotations
import argparse
import csv
import sys
from typing import List, Sequence

import numpy as np
import jax
import jax.numpy as jnp
import equinox as eqx
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

# ── Import sequence mapping tools from base script and model parameters from MLP script ──
from bigru_mixture import AA_TO_ID, sequence_globals
from mlp_mixture import RgMLPNet, mixture_moments, mixture_log_prob

VALID_AA = set("ARNDCQEGHILKMFPSTWYV")


# ══════════════════════════════════════════════════════════════════════════════
# 1.  Checkpoint Loading
# ══════════════════════════════════════════════════════════════════════════════
def load_model(weights_path, stats_path):
    """Rebuild the MLP skeleton from the saved hyper-parameters, then load the weights.

    Architectural configurations (width, depth, n_comp) are read directly from
    the stats file to prevent checkpoint deserialization mismatches.
    """
    s = dict(np.load(stats_path, allow_pickle=True))

    required = ("g_mu", "g_sd", "nu", "log_a", "n_comp", "width", "depth")
    missing = [k for k in required if k not in s]
    if missing:
        raise KeyError(
            f"{stats_path} is missing {missing}. Ensure you are pointing to a "
            f"dense MLP stats file (*_stats.npz) generated by mlp_mixture.py."
        )

    n_comp = int(s["n_comp"])
    width  = int(s["width"])
    depth  = int(s["depth"])

    n_globals = int(np.asarray(s["g_mu"]).shape[0])

    skeleton = RgMLPNet(
        key=jax.random.PRNGKey(0),
        flory_nu=float(s["nu"]), flory_log_a=float(s["log_a"]),
        width=width, depth=depth,
        n_globals=n_globals, n_comp=n_comp,
    )
    model = eqx.tree_deserialise_leaves(weights_path, skeleton)

    print(f"[model] loaded {weights_path} | MLP width={width} depth={depth} K={n_comp} | "
          f"Flory: log Rg = {float(s['log_a']):.4f} + {float(s['nu']):.4f} log N")
    return model, s


# ══════════════════════════════════════════════════════════════════════════════
# 2.  Featurisation (Sequence to Global Descriptors)
# ══════════════════════════════════════════════════════════════════════════════
def clean_sequence(seq, name="<seq>"):
    """Uppercase, strip whitespace, and refuse non-standard residues explicitly."""
    s = "".join(seq.split()).upper()
    bad = sorted(set(s) - VALID_AA)
    if bad:
        raise ValueError(
            f"{name}: non-standard residue(s) {bad}. Drop or replace them explicitly "
            f"before submitting to feature compilation maps."
        )
    if not s:
        raise ValueError(f"{name}: empty sequence")
    return s


def featurize(seqs: Sequence[str], stats, names=None):
    """seqs -> (glob, logL) processed directly into vectorized feature matrix blocks."""
    names = names or [f"seq{i}" for i in range(len(seqs))]
    seqs = [clean_sequence(s, n) for s, n in zip(seqs, names)]

    B = len(seqs)
    n_globals = int(np.asarray(stats["g_mu"]).shape[0])
    glob = np.zeros((B, n_globals), np.float32)
    logL = np.zeros(B, np.float32)

    for i, s in enumerate(seqs):
        tokens = np.array([AA_TO_ID.get(a, 0) for a in s.upper()], dtype=np.int32)
        glob[i] = sequence_globals(tokens)
        logL[i] = np.log(len(tokens) + 1e-6)

    # ── Standardize global physical features using training fold stats ──
    glob = (glob - stats["g_mu"]) / stats["g_sd"]

    return jnp.array(glob, jnp.float32), jnp.array(logL, jnp.float32)


@eqx.filter_jit
def _forward(model, glob, logL):
    return jax.vmap(model)(glob, logL)


def predict(model, stats, seqs, names=None):
    """-> dict of arrays: logit_pi, mu, sigma, mean, std, skew, exkurt (all (B,...))"""
    glob, logL = featurize(seqs, stats, names)
    logit_pi, mu, sigma = _forward(model, glob, logL)
    m1, sd, sk, ku = jax.vmap(mixture_moments)(logit_pi, mu, sigma)
    return dict(
        logit_pi=np.asarray(logit_pi), mu=np.asarray(mu), sigma=np.asarray(sigma),
        mean=np.asarray(m1), std=np.asarray(sd),
        skew=np.asarray(sk), exkurt=np.asarray(ku),
        length=np.array([len(s) for s in seqs]),
    )


# ══════════════════════════════════════════════════════════════════════════════
# 3.  Density Evaluation
# ══════════════════════════════════════════════════════════════════════════════
def density_grid(mu, sigma, n=1000, pad=4.5):
    """Adaptive grid in Rg, spanning the mixture's own support parameters."""
    lo = float(np.exp(mu.min() - pad * sigma.max()))
    hi = float(np.exp(mu.max() + pad * sigma.max()))
    lo = max(lo * 0.75, 1e-3)
    return jnp.linspace(lo, hi * 1.05, n)


def eval_density(logit_pi, mu, sigma, grid):
    return np.asarray(jnp.exp(mixture_log_prob(
        jnp.asarray(logit_pi), jnp.asarray(mu), jnp.asarray(sigma), grid)))


def component_densities(logit_pi, mu, sigma, grid):
    """Each pi_k-weighted log-normal component separately for the plot visualizer."""
    pi = np.asarray(jax.nn.softmax(jnp.asarray(logit_pi)))
    g = np.asarray(grid)
    out = []
    for k in range(len(mu)):
        y = np.log(np.clip(g, 1e-8, None))
        comp = (np.exp(-0.5 * ((y - mu[k]) / sigma[k]) ** 2)
                / (sigma[k] * np.sqrt(2 * np.pi) * np.clip(g, 1e-8, None)))
        out.append(pi[k] * comp)
    return out, pi


# ══════════════════════════════════════════════════════════════════════════════
# 4.  Plots & Visualizations
# ══════════════════════════════════════════════════════════════════════════════
def plot_single(p, i, unit, out_path, show_components=True, ref_rg=None, title=None):
    lp, mu, sg = p["logit_pi"][i], p["mu"][i], p["sigma"][i]
    m1, sd = float(p["mean"][i]), float(p["std"][i])
    sk, ku = float(p["skew"][i]), float(p["exkurt"][i])
    K = len(mu)

    grid = density_grid(mu, sg)
    g = np.asarray(grid)
    dens = eval_density(lp, mu, sg, grid)

    fig, ax = plt.subplots(figsize=(7.6, 4.6))
    ax.fill_between(g, dens, alpha=0.22, color="#2ca02c")
    ax.plot(g, dens, color="#2ca02c", lw=2.3, label="Predicted mixture", zorder=3)

    if show_components:
        comps, pi = component_densities(lp, mu, sg, grid)
        order = np.argsort(-pi)
        for rank, k in enumerate(order):
            if pi[k] < 1e-3: 
                continue
            ax.plot(g, comps[k], lw=1.0, alpha=0.75, ls="-",
                    color=plt.cm.viridis(rank / max(K - 1, 1)),
                    label=f"comp {k} ($\\pi$={pi[k]:.2f})" if rank < 4 else None,
                    zorder=2)

    gauss = np.exp(-0.5 * ((g - m1) / sd) ** 2) / (sd * np.sqrt(2 * np.pi))
    ax.plot(g, gauss, "--", color="#7f7f7f", lw=1.3,
            label="Gaussian (same $\\mu,\\sigma$)", zorder=1)

    ax.axvline(m1, color="#d62728", ls=":", lw=1.5, zorder=4)
    if ref_rg is not None:
        ax.axvline(ref_rg, color="#1f77b4", ls="-.", lw=1.5, zorder=4,
                   label=f"Reference ({ref_rg:.2f} {unit})")

    ax.set_xlim(g.min(), g.max())
    ax.set_ylim(bottom=0)
    ax.set_xlabel(f"Radius of gyration $R_g$ [{unit}]")
    ax.set_ylabel("Probability density")
    ax.set_title(title or f"Predicted $P(R_g)$ — MLP log-normal mixture, K={K}")

    txt = (f"L        = {int(p['length'][i])}\n"
           f"mean     = {m1:.2f} {unit}\n"
           f"std      = {sd:.2f} {unit}\n"
           f"skew     = {sk:+.3f}\n"
           f"ex-kurt  = {ku:+.3f}")
    ax.text(0.975, 0.94, txt, transform=ax.transAxes, ha="right", va="top",
            fontsize=9, family="monospace",
            bbox=dict(boxstyle="round", facecolor="white", edgecolor="#ddd", alpha=0.92))
    ax.legend(loc="upper left", frameon=False, fontsize=8.5)
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)
    print(f"[plot] density -> {out_path}")


def plot_benchmark(names, pred, ref, unit, out_path, annotate=None, pred_err=None):
    from scipy.stats import pearsonr, spearmanr

    pred = np.asarray(pred, float)
    ref  = np.asarray(ref, float)

    r, _   = pearsonr(ref, pred)
    rho, _ = spearmanr(ref, pred)
    ss_res = np.sum((ref - pred) ** 2)
    ss_tot = np.sum((ref - ref.mean()) ** 2)
    r2   = 1.0 - ss_res / ss_tot          
    mae  = np.mean(np.abs(ref - pred))
    rmse = np.sqrt(np.mean((ref - pred) ** 2))
    bias = np.mean(pred - ref)            

    fig, ax = plt.subplots(figsize=(6.4, 6.4))
    lo = min(ref.min(), pred.min())
    hi = max(ref.max(), pred.max())
    span = hi - lo
    lo, hi = lo - 0.08 * span, hi + 0.08 * span

    ax.plot([lo, hi], [lo, hi], "--", color="#7f7f7f", alpha=0.75, lw=1.3,
            label="Identity ($y=x$)", zorder=1)
    ax.fill_between([lo, hi], [lo * 0.9, hi * 0.9], [lo * 1.1, hi * 1.1],
                    color="#7f7f7f", alpha=0.08, zorder=0, label="±10%")

    if pred_err is not None:
        ax.errorbar(ref, pred, yerr=np.asarray(pred_err), fmt="none",
                    ecolor="#1f77b4", alpha=0.35, elinewidth=1.1, capsize=2, zorder=2)
    ax.scatter(ref, pred, color="#1f77b4", s=48, alpha=0.85,
               edgecolors="white", linewidths=0.6, zorder=3)

    ann = set(annotate or names)
    for i, nm in enumerate(names):
        if nm in ann:
            ax.annotate(nm, (ref[i], pred[i]), textcoords="offset points",
                        xytext=(0, 7), ha="center", fontsize=7.5, color="#333")

    ax.set_xlim(lo, hi); ax.set_ylim(lo, hi)
    ax.set_aspect("equal", "box")
    ax.set_xlabel(f"Simulation $R_g$ [{unit}]")
    ax.set_ylabel(f"Predicted mean $R_g$ [{unit}]")
    ax.set_title("MLP Mixture Head Model — Prediction vs Simulated Rg")

    txt = (f"n     = {len(ref)}\n"
           f"r     = {r:.3f}\n"
           f"rho   = {rho:.3f}\n"
           f"R^2   = {r2:.3f}\n"
           f"MAE   = {mae:.3f} {unit}\n"
           f"RMSE  = {rmse:.3f} {unit}\n"
           f"bias  = {bias:+.3f} {unit}")
    ax.text(0.04, 0.96, txt, transform=ax.transAxes, ha="left", va="top",
            fontsize=9, family="monospace",
            bbox=dict(boxstyle="round", facecolor="white", edgecolor="#ddd", alpha=0.92))
    ax.legend(loc="lower right", frameon=False, fontsize=8.5)
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)
    print(f"[plot] benchmark -> {out_path}")
    return dict(n=len(ref), pearson=r, spearman=rho, r2=r2, mae=mae, rmse=rmse, bias=bias)


def plot_ridgeline(names, p, unit, out_path, max_show=24):
    n = min(len(names), max_show)
    fig, ax = plt.subplots(figsize=(7.4, 0.42 * n + 1.6))
    lo = min(float(np.exp(p["mu"][i].min() - 4 * p["sigma"][i].max())) for i in range(n))
    hi = max(float(np.exp(p["mu"][i].max() + 4 * p["sigma"][i].max())) for i in range(n))
    grid = jnp.linspace(max(lo * 0.8, 1e-3), hi * 1.05, 800)
    g = np.asarray(grid)

    order = np.argsort(p["mean"][:n])
    for row, i in enumerate(order):
        d = eval_density(p["logit_pi"][i], p["mu"][i], p["sigma"][i], grid)
        d = d / d.max() * 0.85
        y = row
        ax.fill_between(g, y, y + d, color=plt.cm.viridis(row / max(n - 1, 1)), alpha=0.55, lw=0)
        ax.plot(g, y + d, color="#333", lw=0.7)
        ax.plot([p["mean"][i]], [y], marker="|", color="#d62728", ms=7)

    ax.set_yticks(np.arange(n))
    ax.set_yticklabels([names[i] for i in order], fontsize=7.5)
    ax.set_xlabel(f"$R_g$ [{unit}]")
    ax.set_title("Predicted $P(R_g)$ per sequence (red tick = mean)")
    ax.set_xlim(g.min(), g.max())
    ax.spines[["top", "right", "left"]].set_visible(False)
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)
    print(f"[plot] ridgeline -> {out_path}")


# ══════════════════════════════════════════════════════════════════════════════
# 5.  YAML and Metrics Infrastructure
# ══════════════════════════════════════════════════════════════════════════════
def load_yaml(path):
    import yaml
    with open(path) as f:
        y = yaml.safe_load(f)
    if not isinstance(y, dict):
        raise ValueError("sequences.yaml must be a mapping: name -> {sequence: ..., Rg: ...}")

    names, seqs, refs = [], [], []
    for name, v in y.items():
        if isinstance(v, str):                       
            seq, rg = v, None
        elif isinstance(v, dict):
            if "sequence" not in v:
                raise KeyError(f"{name}: no 'sequence' key")
            seq = v["sequence"]
            rg = v.get("Rg", v.get("rg", None))
        else:
            raise TypeError(f"{name}: expected str or mapping, got {type(v).__name__}")
        names.append(name); seqs.append(seq)
        refs.append(float(rg) if rg is not None else np.nan)
    return names, seqs, np.array(refs, float)


def check_units(pred, ref, unit):
    ok = np.isfinite(ref) & np.isfinite(pred)
    if ok.sum() < 2:
        return
    ratio = float(np.median(pred[ok] / ref[ok]))
    if 5.0 < ratio < 20.0:
        print(f"\n[UNITS?] predicted / reference median ratio = {ratio:.2f}. "
              f"Suspected Ångström scaling vs nm table. Fix with: --unit-scale 0.1 --unit nm\n", file=sys.stderr)
    elif 0.05 < ratio < 0.2:
        print(f"\n[UNITS?] predicted / reference median ratio = {ratio:.2f}. "
              f"Suspected nm scaling vs Å table. Fix with: --unit-scale 10 --unit A\n", file=sys.stderr)


def write_csv(path, names, p, ref, unit):
    with open(path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["name", "length", f"pred_mean_{unit}", f"pred_std_{unit}",
                    "pred_skew", "pred_exkurt", f"ref_rg_{unit}", "abs_err", "rel_err"])
        for i, nm in enumerate(names):
            r = ref[i]
            ae = abs(p["mean"][i] - r) if np.isfinite(r) else np.nan
            re_ = ae / r if (np.isfinite(r) and r != 0) else np.nan
            w.writerow([nm, int(p["length"][i]),
                        f"{p['mean'][i]:.4f}", f"{p['std'][i]:.4f}",
                        f"{p['skew'][i]:.4f}", f"{p['exkurt'][i]:.4f}",
                        f"{r:.4f}" if np.isfinite(r) else "",
                        f"{ae:.4f}" if np.isfinite(ae) else "",
                        f"{re_:.4f}" if np.isfinite(re_) else ""])
    print(f"[csv]  -> {path}")


# ══════════════════════════════════════════════════════════════════════════════
# 6.  Self-Test (Vectorized Matrix Execution Invariance)
# ══════════════════════════════════════════════════════════════════════════════
def self_test(model, stats):
    """Verifies that batched MLP row indexing exactly matches single processing passes."""
    seqs = ["MDVFMKGLSKAKEGVVAAAEK",
            "MDVFMKGLSKAKEGVVAAAEKTKQGVAEAAGKTKEGVLYVGSKTKEGVVHGVATVAEKTKEQ",
            "GSHMASMTGGQQMGRDLYDDDDKDRWGSELEKAMVALIDVFHQYSGREGDKHKLKKSELKEL"]
    batched = predict(model, stats, seqs)
    worst = 0.0
    for i, s in enumerate(seqs):
        one = predict(model, stats, [s])
        for k in ("mean", "std", "skew", "exkurt"):
            worst = max(worst, abs(float(one[k][0]) - float(batched[k][i])))
    print(f"[self-test] batched execution invariant verification: max |Δmoment| = {worst:.3e}")
    if worst > 1e-5:
        raise AssertionError(f"Consistency check failed. Variance discrepancy encountered: {worst:.3e}")
    print("[self-test] OK — batched forward indexing operations match scalar evaluation passes.")


# ══════════════════════════════════════════════════════════════════════════════
def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("mode", choices=["single", "benchmark", "selftest"])
    ap.add_argument("--weights", default="rg_mlp_model.eqx")
    ap.add_argument("--stats",   default="rg_mlp_stats.npz")
    ap.add_argument("--unit", default="A", help="label for the Rg axis (A, nm, ...)")
    ap.add_argument("--unit-scale", type=float, default=1.0)
    # single
    ap.add_argument("--seq", default=None, help="one sequence (single mode)")
    ap.add_argument("--ref", type=float, default=None, help="reference Rg to overlay")
    # benchmark
    ap.add_argument("--yaml", default="config/sequences.yaml")
    ap.add_argument("--csv", default=None)
    ap.add_argument("--ridgeline", default=None)
    ap.add_argument("--annotate", nargs="*", default=None)
    ap.add_argument("--out", default=None)
    a = ap.parse_args()

    model, stats = load_model(a.weights, a.stats)
    sc = a.unit_scale

    if a.mode == "selftest":
        self_test(model, stats)
        return

    if a.mode == "single":
        if not a.seq:
            ap.error("single mode requires argument input context mapping to --seq")
        p = predict(model, stats, [a.seq])
        for k in ("mean", "std"):
            p[k] = p[k] * sc
        m1, sd = float(p["mean"][0]), float(p["std"][0])
        sk, ku = float(p["skew"][0]), float(p["exkurt"][0])
        p["mu"] = p["mu"] + np.log(sc)
        
        print(f"\n[prediction]  L = {int(p['length'][0])}")
        print(f"  mean Rg   {m1:8.3f} {a.unit}")
        print(f"  std Rg    {sd:8.3f} {a.unit}   (CV = {sd/m1:.3f})")
        print(f"  skew      {sk:+8.3f}")
        print(f"  ex-kurt   {ku:+8.3f}")
        pi = np.asarray(jax.nn.softmax(jnp.asarray(p["logit_pi"][0])))
        print(f"  live components (pi>0.01): {int((pi > 0.01).sum())}/{len(pi)}  "
              f"pi = {np.array2string(pi, precision=3, suppress_small=True)}")
        plot_single(p, 0, a.unit, a.out or "rg_density.png", ref_rg=a.ref)
        return

    # ── Benchmark Mode Execution ──
    names, seqs, ref = load_yaml(a.yaml)
    print(f"[yaml] {len(names)} sequences compiled from {a.yaml}")
    p = predict(model, stats, seqs, names)
    p["mean"] = p["mean"] * sc
    p["std"]  = p["std"] * sc
    p["mu"]   = p["mu"] + np.log(sc)

    print(f"\n{'name':<20s} {'L':>4s} {'pred':>9s} {'std':>7s} {'skew':>7s} {'exkurt':>7s} {'ref':>9s} {'err':>8s}")
    print("─" * 82)
    for i, nm in enumerate(names):
        r = ref[i]
        err = f"{p['mean'][i] - r:+8.3f}" if np.isfinite(r) else "       —"
        rs = f"{r:9.3f}" if np.isfinite(r) else "        —"
        print(f"{nm:<20s} {int(p['length'][i]):4d} {p['mean'][i]:9.3f} "
              f"{p['std'][i]:7.3f} {p['skew'][i]:+7.3f} {p['exkurt'][i]:+7.3f} "
              f"{rs} {err}")

    check_units(p["mean"], ref, a.unit)

    if a.csv:
        write_csv(a.csv, names, p, ref, a.unit)
    if a.ridgeline:
        plot_ridgeline(names, p, a.unit, a.ridgeline)

    ok = np.isfinite(ref)
    if ok.sum() < 2:
        print("\n[skip] Missing necessary numerical variance counts inside YAML configuration maps.")
        return

    m = plot_benchmark([n for n, k in zip(names, ok) if k],
                       p["mean"][ok], ref[ok], a.unit,
                       a.out or "model_vs_reference.png",
                       annotate=a.annotate,
                       pred_err=p["std"][ok])
    print(f"\n[metrics] n={m['n']}  r={m['pearson']:.3f}  rho={m['spearman']:.3f}  "
          f"R2={m['r2']:.3f}  MAE={m['mae']:.3f}  RMSE={m['rmse']:.3f}  "
          f"bias={m['bias']:+.3f} {a.unit}")


if __name__ == "__main__":
    main()